app:
  name: "wleowleo"
  logLevel: 4
  env: "development"

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  exchange: "wleowleo"
  queue:
    scraperCommandQueue: "scraper_command"
    videoLinksQueue: "scraper_video_queue"
    scraperLogQueue: "scraper_log"
  reconnectRetries: 5
  reconnectTimeout: 10000 # ms

scraper:
  host: "https://viral.waptrick.men"
  startPage: 1
  endPage: 2
  userAgent: "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Mobile Safari/537.36"

downloader:
  concurrency: 2
  tempDir: "./temp"
  downloadDir: "./downloads"

webpanel:
  host: "localhost"
  port: 8080
